name: disproject
version: "0.0.0"

dependencies:
  - base >=4.9.1.0 && <5
  - yesod >=1.6.0.0 && <1.8.0
  - yesod-core >=1.6.7 && <1.8.0
  - yesod-auth >=1.6.7 && <1.8.0
  - yesod-auth-oauth2 >=0.6 && <0.8
  - yesod-static >=1.6.0.0 && <1.8.0
  - yesod-form >=1.6.7 && <1.8.0
  - classy-prelude >=1.5 && <1.6
  - classy-prelude-conduit >=1.5 && <1.6
  - classy-prelude-yesod >=1.5 && <1.6
  - bytestring >=0.10 && <0.11
  - text >=0.11 && <2.0
  - persistent >=2.10.0.0 && <2.14.0.2
  - persistent-postgresql >=2.10.0.0 && <2.14.0.2
  - persistent-template >=2.8.0 && <2.13.0.0
  - template-haskell
  - shakespeare >=2.0 && <2.1
  - hjsmin >=0.1 && <0.3
  - monad-control >=0.3 && <1.1
  - wai-extra >=3.1.0 && <3.1.12.1
  - yaml >=0.11 && <0.12
  - http-client-tls >=0.3 && <0.4
  - http-conduit >=2.3 && <2.4
  - directory >=1.1 && <1.4
  - warp >=3.0 && <3.4
  - data-default
  - aeson >=2.0 && <2.2
  - conduit >=1.0 && <2.0
  - monad-logger >=0.3 && <0.4
  - fast-logger >=2.2 && <3.1
  - wai-logger >=2.2 && <2.4
  - file-embed
  - safe
  - unordered-containers
  - containers
  - vector
  - time
  - case-insensitive
  - wai
  - foreign-store
  - markdown
  - yesod-text-markdown >=0.1.9 && <0.2
  - transformers >=0.4 && <0.6
  - word8
  - hoauth2 >=2.0.0 && <2.6.0
  - blaze-builder

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
    - condition: (flag(dev)) || (flag(library-only))
      then:
        ghc-options:
          - -Wall
          - -fwarn-tabs
          - -O0
        cpp-options: -DDEVELOPMENT
      else:
        ghc-options:
          - -Wall
          - -fwarn-tabs
          - -O2

# Runnable executable for our application
executables:
  disproject:
    main: main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - disproject
    when:
      - condition: flag(library-only)
        buildable: false

# Test suite
tests:
  disproject-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
      - disproject
      - hspec >=2.0.0
      - yesod-test

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
